# Generated by Django 2.2 on 2020-06-29 18:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200628_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(default='')), ('paragraph', wagtail.core.blocks.RichTextBlock(default=''))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_me',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(default='')), ('paragraph', wagtail.core.blocks.RichTextBlock(default=''))]),
        ),
    ]
