# Generated by Django 2.2 on 2020-07-01 18:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200629_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='portfolio',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(default='Portfolio')), ('card', wagtail.core.blocks.StructBlock([('app_name', wagtail.core.blocks.CharBlock()), ('app_url', wagtail.core.blocks.URLBlock(required=False)), ('app_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('summary', wagtail.core.blocks.RichTextBlock()), ('achievements', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(label='Achievement')))]))], default=''),
            preserve_default=False,
        ),
    ]
