# Generated by Django 2.2 on 2020-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
