# Generated by Django 2.2 on 2019-07-20 21:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.TextField()),
                ('path', models.URLField(blank=True, max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('geoip_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
